server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    title: "商品服务接口文档"
    package: com.heima.trade.controller

spring:
  rabbitmq:
    host: 192.168.5.67 # 你的虚拟机IP
    port: 5673 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码

    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
