server:
  port: 8084

hm:
  db:
    database: hm-user
  swagger:
    title: "商品服务接口文档"
    package: com.heima.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m