server:
  port: 8082
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connections: 100
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true
hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    host: 192.168.5.112
    port: 3306
    database: hm-cart
    un: root
    pw: 34793479

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.5.67:8090
      http-method-specify: true #请求方式(GET,POST...) + 路径 作为资源名称