server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.5.67:8848
    gateway:
      routes:
        - id: item-service #    路由规则id，自定义，唯一
          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表 (查看对应的yam文件里的名字)
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/items/**,/search/** # 这里是以请求路径作为判断规则(查看对应的controller里的路径)
        - id: user-service #    路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表 (查看对应的yam文件里的名字)
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/addresses/**,/users/** # 这里是以请求路径作为判断规则(查看对应的controller里的路径)
        - id: cart-service #    路由规则id，自定义，唯一
          uri: lb://cart-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表 (查看对应的yam文件里的名字)
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/carts/** # 这里是以请求路径作为判断规则(查看对应的controller里的路径)
      default-filters:
        - AddRequestHeader=truth, anyone long-press like button will be rich
        - PrintAny
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**